name: Mac 

# syntax https://help.github.com/en/articles/workflow-syntax-for-github-actions
on:
  push:
    branches: 
      - '*'
    tags:
      - '*'
    
jobs:
  conda:
    name: conda-build

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Download MacOSX 10.9 SDK
      run: |
        wget https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX10.9.sdk.tar.xz
        tar -xf MacOSX10.9.sdk.tar.xz
        echo 'CONDA_BUILD_SYSROOT:' > conda_build_config.yaml
        echo "  - $GITHUB_WORKSPACE/MacOSX10.9.sdk" >> conda_build_config.yaml
        cat conda_build_config.yaml

    - name: Install Conda
      run: |
        brew cask install miniconda
        echo "shell: ${SHELL}"
        conda init "$(basename ${SHELL})"
        echo "path: $PATH"

    - name: Deploy Conda package
      run: |
        source ~/.bash_profile
        echo "path: $PATH"
        conda create -n packaging --channel conda-forge conda-build anaconda-client conda-verify
        conda activate packaging
        conda config --set anaconda_upload yes
        # Use unique hostname to avoid warning about multiple logins with the
        # same hostname.
        # https://gist.github.com/earthgecko/3089509
        ANACONDA_HOSTNAME=$(perl -e '@c=("A".."Z","a".."z",0..9);$p.=$c[rand(scalar @c)] for 1..32; print "$p\n"')
        echo "ANACONDA_HOSTNAME: $ANACONDA_HOSTNAME"
        conda-build --channel conda-forge --user opensim-org --token ${{ secrets.ANACONDA_TOKEN }} .
        anaconda logout
