name: Mac 

# syntax https://help.github.com/en/articles/workflow-syntax-for-github-actions
on:
  push:
    branches: 
      - '*'
    tags:
      - '*'
    
jobs:
  mac:
    name: conda-build

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Download MacOSX 10.9 SDK
      run: |
        wget https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX10.9.sdk.tar.xz
        tar -xf MacOSX10.9.sdk.tar.xz
        echo 'CONDA_BUILD_SYSROOT:' > conda_build_config.yaml
        echo '$GITHUB_WORKSPACE/MacOSX10.9.sdk' >> conda_build_config.yaml

    - name: Install Conda
      run: |
        brew cask install miniconda
        conda init "$(basename ${SHELL})"
        exec zsh

    - name: Deploy Conda package
      run: |
        conda create -n packaging --channel conda-forge conda-build anaconda-client conda-verify
        source activate packaging
        conda config --set anaconda_upload yes
        anaconda login --username {{ secrets.ANACONDA_USERNAME }} --password {{ secrets.ANACONDA_PASSWORD }}
        conda-build --channel conda-forge --user opensim-org .
        anaconda logout
