name: conda-build

# syntax https://help.github.com/en/articles/workflow-syntax-for-github-actions
on:
  push:
    branches: 
      - '*'
    tags:
      - '*'
    
jobs:
  mac:
    name: Mac

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Download MacOSX 10.9 SDK
    - run: |
        wget https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX10.9.sdk.tar.xz
        tar -xf MacOSX10.9.sdk
        echo 'CONDA_BUILD_SYSROOT:' > conda_build_config.yaml
        echo '$GITHUB_WORKSPACE/MacOSX10.9.sdk' >> conda_build_config.yaml

    - name: Deploy Conda package
      run: |
        conda create -n packaging --channel conda-forge conda-build anaconda-client
        conda activate packaging
        conda config --set anaconda_upload yes
        anaconda login --username {{ secrets.ANACONDA_USERNAME }} --password {{ secrets.ANACONDA_PASSWORD }}
        conda build --channel conda-forge .
        anaconda logout
