name: Windows

# syntax https://help.github.com/en/articles/workflow-syntax-for-github-actions
on:
  push:
    branches: 
      - '*'
    tags:
      - '*'
    
jobs:
  windows:
    name: conda-build

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Initialize Conda for Powershell
      run: |
        (Get-Command python).Path
        C:\Miniconda/condabin/conda.bat create -n packaging --channel conda-forge conda-build anaconda-client conda-verify
        C:\Miniconda/condabin/conda.bat init powershell

    - name: Deploy Conda package
      run: |
        echo "activate"
        conda activate packaging
        echo "config"
        conda config --set anaconda_upload yes
        echo "login"
        anaconda login --username ${{ secrets.ANACONDA_USERNAME }} --password ${{ secrets.ANACONDA_PASSWORD }}
        echo "build"
        conda-build --channel conda-forge --user opensim-org .
        echo "logout"
        anaconda logout
