name: Ubuntu

# syntax https://help.github.com/en/articles/workflow-syntax-for-github-actions
on:
  push:
    branches: 
      - '*'
    tags:
      - '*'
    
jobs:
  conda:
    name: conda-build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Initialize Conda
      run: |
        echo "shell: ${SHELL}"
        conda init "$(basename ${SHELL})"
        echo "path: $PATH"

    - name: Deploy Conda package
      run: |
        cat ~/.bashrc
        # source ~/.bashrc
        source /usr/share/miniconda/etc/profile.d/conda.sh
        echo "path: $PATH"
        conda create -n packaging --channel conda-forge conda-build anaconda-client conda-verify
        conda activate packaging
        conda config --set anaconda_upload yes
        conda-build --channel conda-forge --user opensim-org --token ${{ secrets.ANACONDA_TOKEN }} .
        anaconda logout
